[package]
name = "task-tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["clock"] }
serde = { version = "1.0.219", features = ["derive"] } 
serde_json = "1.0.142"

[[bin]]
name = "task-cli"
path = "src/main.rs"
